### ISSUE TITLE
MDL Importer

### ISSUE THREAD

**Issue by NiklasSabel** [niklasadams/PrecisionFitnessOCPM#1]
Hey,

when trying to prepare the code in my environment, I run into the problem that the ocpa package doesn't seem to contain an mdl importer anymore.

Which version of ocpa was used in the code?

**Comment by niklasadams** [comment]
Hi Niklas,
There are two possible options:
1. Locally installing (e.g. with pip) the old (outdated) ocpa repository https://github.com/gyunamister/ocpa
2. Using the import from the new ocpa. We have an example script for precision and fitness here: https://github.com/ocpm/ocpa/blob/main/example-scripts/conformance-checking/precision_and_fitness.py
I would recommend the second option as you also have access to the other functionality. 
Does that help?
Best
Niklas

**Comment by NiklasSabel** [comment]
Hey Niklas,

yes thanks a lot!

Best,
Niklas
